### ISSUE TITLE
CSV_READ Error

### ISSUE THREAD

**Issue by abe-mart** [BYU-PRISM/GEKKO#1]
The HS71 example returns the error "CSV_READ was not written correctly" in steady state optimization mode.

**Comment by loganbeal** [comment]
GEKKO compares the option values it wrote to APMonitor with the options that APMonitor says it used. In this case, GEKKO defaults to telling APMonitor to read the .csv file (default is CSV_READ=2) but APMonitor reported CSV_READ=0 because it didn't read a .csv file. In this case it's because there's not a csv file because it's steady state and all values are communicated through the apm file.
Solutions include:
1. Changing APMonitor to not change CSV_READ if it didn't read a file.
2. Telling GEKKO to ignore this comparison if a csv file isn't written.

**Comment by loganbeal** [comment]
This has been fixed by registering internally if a csv file was written. The comparison is ignored if a csv was not written. 
Please confirm the expected behavior.

**Comment by abe-mart** [comment]
Fixed.
