### ISSUE TITLE
Using sklearn methods inside Gekko equation

### ISSUE THREAD

**Issue by pavankumarg1729** [BYU-PRISM/GEKKO#128]
I am working on an optimization problem using Gekko and i need to pass in the prediction from a pre built model using Sklearn. I am not able to use predict.proba method using Gekko problem statement. Is there any way to solve this problem?

**Comment by APMonitor** [comment]
You can pass in a "Measured" value to Gekko with `x.value=15.0` to update the value. There is no way to import equations from `sklearn` into `gekko` right now because Gekko solvers need the equations in Gekko format for automatic differentiation. Gekko doesn't allow black box models at this time. If you need an optimizer for black box models, try `scipy.optimize.minimize()`.
