### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by Mechanikrow** [BYU-PRISM/GEKKO#181]

**Comment by APMonitor** [comment]
Hi Mechanikrow,

Thank you for reaching out. Your issue doesn't include specific details about the Gekko project. If you have any requested features, concerns, or feedback regarding Gekko please provide more details so we can assist you effectively.

For now, I'll be closing this issue due to lack of details, but please don't hesitate to open a new issue with more information if there's something specific you need help with. For question regarding the Gekko modeling language, please ask on Stack Overflow: https://stackoverflow.com/questions/tagged/gekko
