### ISSUE TITLE
Final Values

### ISSUE THREAD

**Issue by abe-mart** [BYU-PRISM/GEKKO#2]
It seems like final value constraints come up enough in dynamic problems that it would be worth adding them directly to the interface.  Something like x.final = 0 perhaps?

**Comment by loganbeal** [comment]
This is a great idea that would best be solved with connections, which are not yet implemented.

**Comment by loganbeal** [comment]
@abe-mart This has been implemented through the fix() and Connection() commands ([docs](http://gekko.readthedocs.io/en/latest/model_methods.html#model-building)).
Note that we have discovered a logic bug in the APM backend since this function was released: the derivative values are also fixed at the same point as the value. This can cause infeasibilities or strange behavior when fixing a variable that is also differentiated.
