### ISSUE TITLE
Failed to start GPU process

### ISSUE THREAD

**Issue by dhill2522** [BYU-PRISM/GEKKO#25]
This nasty-looking error has come up when running `m.GUI()` to launch the gui on some machines. 

![image](https://user-images.githubusercontent.com/18505571/37795298-b5ec64c6-2dd9-11e8-9f6e-de0c11bee1f8.png)

As far as I can tell this is not actually an issue with the Gekko project itself, but is actually an error being thrown from chromium in this case. It is also a problem for our friends on the jupyter project as is evidenced in their [issue 2836](https://github.com/jupyter/notebook/issues/2836)

**Comment by dhill2522** [comment]
@loganbeal would you mind trying some of the suggestions from our friends in the above jupyter issue and seeing if that resolves your problem? I have not been able to reproduce it here.

**Comment by loganbeal** [comment]
`export BROWSER="chromium-browser"` before launching spyder does resolve this issue. Is this a reasonable long-term solution? Should we just add a note in the docs to set the appropriate BROWSER environment variable if you're experiencing this issue?

Interestingly,  `export BROWSER="google-chrome"` launches chrome instead of chromium, but chrome can't connect to the server (`localhost refused to connect`) and the kernel restarts automatically.
Also interestingly, I get the same gpu error when launching chromium or chrome from the CLI:
```
> chromium-browser 
> Created new window in existing browser session.
[11751:11785:0322/144201.450026:ERROR:browser_gpu_channel_host_factory.cc(121)] Failed to launch GPU process.
```

**Comment by dhill2522** [comment]
Maybe we do want to just put a note in the docs until the problem seems to go away or we learn more about it. Either way I do not think it is an issue with our code, so I am closing this out.
