### ISSUE TITLE
Application not cleared with m.solve(remote=True)

### ISSUE THREAD

**Issue by APMonitor** [BYU-PRISM/GEKKO#27]
GEKKO needs to clear the application on the first cycle when remote=True else certain files become very large such as overrides.dbs and 127.0.0.1_gk_model0.info. Options also persist from prior applications. I tested this with m.server='http://127.0.0.1' and repeatedly solved a problem such as would happen with mhe or mpc. The INFO file has 3354 lines (all from 1 MV and 1 CV declared) and the overrides.dbs file is over 600 KB. Adding to the file each solve will make it large and will slow down the execution as all the lines are parsed.

I recommend two possible things:
1. Clear the application before uploading files. See line 313 of https://github.com/APMonitor/apm_python/blob/master/apm.py - the files are cleared by sending the command 'clear all'. An alternative is to give the server application a random name as is done with the local directory.
2. Replace the files (info and overrides.dbs) each cycle. I may need to update the server PHP to allow this.

I'd like to run GEKKO for a couple weeks, months, or years with scheduled cycles and want to make sure that the application doesn't slow down when running either on a remote server or else on a localhost server.

I could also do something on the APM side to manage the overrides.dbs and info file size like is done with measurements.dbs where the file contents are deleted when a measurement is read. Only the last measurement in the list is implemented so it is okay to have a separate process sending a stream of measurements to the file - it will always use the most updated measurement. The overrides.dbs and info files would be different in that I'd only keep the latest definitions. The one thing that this can't manage is information from a prior application such as MV, FV, or CV declarations.

**Comment by loganbeal** [comment]
GEKKO does clear the server on model initialization

```
    def __init__(self, server='http://byu.apmonitor.com', name=None):
        self.server = compatible_string_strip(server)
        ...
        #clear anything already on the server
        cmd(self.server,self.model_name,'clear all')
```
However, model initialization happens on m=GEKKO(). If you set the server with `m.server='http://127.0.0.1'` after model initialization, then this server is not cleared. Instead, set the server when you initialize the model `m = GEKKO(server='http://127.0.0.1')`

Nevertheless, the dbs and info files can get quite large since the server files append rather than overwrite. I have circumvented this in commit dd2b783335492c05a14c69714a543136ef7a4b0a by using measurements.dbs (rather than overrides.dbs) so the APM executable will clean up used options. Should I use problemname.dbs instead? 

> The DBS files are read next, starting with defaults.dbs and finishing with overrides.dbs. Most of the problem configuration information is stored in problem.dbs. This file is re-written every cycle and contains all of the information set by other DBS files or values that are adjusted by validity limit checks.

I also only write the info file when CYCLECOUNT<1. Since GEKKO doesn't support changing variable types, the information in the info file doesn't change. Even though there may be a few unsuccessful solves before CYLCECOUNT is incremented, this should at least keep the file at a reasonable size.

These changes are implemented in release 0.0.4rc1, released today. Please confirm the expected behavior on a remote server.
