### ISSUE TITLE
CSV_READ behavior

### ISSUE THREAD

**Issue by abe-mart** [BYU-PRISM/GEKKO#5]
What is the current behavior of the csv_read option in GEKKO?

**Comment by loganbeal** [comment]
@abe-mart Values assigned to GEKKO variables are communicated through the csv file. If csv_read = 0, only scalar values of parameters and variables are read through the .apm file. If csv_read=1, all parameter values are also read in. If csv_read=2, all parameter and (initial) variable values are loaded.
The default GEKKO value is 2.
Only values defined by the user since model initialization or the last solve are written to the csv. All other values are loaded back from the APM internal .t0 database files and timeshifted according to the time_shift option.
If a measurement (.meas) is defined, the associated variable value is not written to the csv. Also, if a variable value is fixed with the fix() command, the fixed value is written in the csv file.

**Comment by abe-mart** [comment]
Good information, thank you.  This could be a helpful addition to the documentation.

**Comment by loganbeal** [comment]
I added this information to the documentation under CSV_READ.
